import {test} from 'node:test';import assert from 'node:assert/strict';import {GameRoom,emptyState} from '../src/game.js';import worker from '../src/worker.js';
function socket(){return {readyState:1,a:{id:null,at:Date.now(),count:0},out:[],serializeAttachment(v){this.a=v},deserializeAttachment(){return this.a},send(s){this.out.push(JSON.parse(s))},close(){this.readyState=3}}}
async function fixture(){const sockets=[socket(),socket(),socket()];let saved;let ready;const ctx={getWebSockets:()=>sockets,storage:{get:async()=>saved,put:async(k,v)=>{saved=structuredClone(v)}},blockConcurrencyWhile:f=>{ready=f()}};const g=new GameRoom(ctx);await ready;const tokens=[crypto.randomUUID(),crypto.randomUUID()];for(let i=0;i<2;i++)await g.webSocketMessage(sockets[i],JSON.stringify({type:'join',token:tokens[i],name:'사용자'+i}));return {g,sockets,ctx,tokens,ready:()=>ready};}
const msg=(g,s,m)=>g.webSocketMessage(s,JSON.stringify(m));
test('두 명 입장, 세 번째 거절 및 비밀 토큰 비공개',async()=>{const {g,sockets}=await fixture();assert.equal(g.state.status,'playing');await msg(g,sockets[2],{type:'join',token:crypto.randomUUID()});assert.equal(sockets[2].readyState,3);assert(!JSON.stringify(sockets[0].out).includes('token'));});
test('상대 ID 사칭 및 잘못된 착수 차단',async()=>{const {g,sockets}=await fixture();g.state.turn=0;await msg(g,sockets[1],{type:'move',id:g.state.players[0].id,index:0});assert.equal(g.state.board[0],0);for(const index of [-1,225,'0',1.2,null])await msg(g,sockets[0],{type:'move',index});assert(g.state.board.every(x=>x===0));await msg(g,sockets[0],{type:'move',index:112});assert.equal(g.state.board[112],1);await msg(g,sockets[1],{type:'move',index:112});assert.equal(g.state.turn,1);});
test('가로 세로 양 대각선 및 장목 승리, 줄넘김 방지',async()=>{const {g}=await fixture();for(const line of [[0,1,2,3,4],[0,15,30,45,60],[0,16,32,48,64],[4,18,32,46,60],[0,1,2,3,4,5]]){g.state.board=Array(225).fill(0);line.forEach(i=>g.state.board[i]=1);assert(g.win(line[2],1));}g.state.board=Array(225).fill(0);[13,14,15,16,17].forEach(i=>g.state.board[i]=1);assert.equal(g.win(15,1),false);});
test('실제 교대 착수 승리 후 양쪽 동의로 재대전',async()=>{const {g,sockets}=await fixture();g.state.turn=g.state.starter=g.state.black=0;await msg(g,sockets[0],{type:'move',index:112});await msg(g,sockets[1],{type:'move',index:30});for(let i=0;i<4;i++){await msg(g,sockets[0],{type:'move',index:i});await msg(g,sockets[1],{type:'move',index:45+i});}await msg(g,sockets[0],{type:'move',index:4});assert.equal(g.state.status,'won');await msg(g,sockets[0],{type:'rematch'});assert.equal(g.state.status,'won');await msg(g,sockets[1],{type:'rematch'});assert.equal(g.state.status,'playing');assert.equal(g.state.turn,1);assert(g.state.board.every(x=>!x));});
test('진행 중 재대전 요청 무시',async()=>{const {g,sockets}=await fixture();await msg(g,sockets[0],{type:'rematch'});assert.deepEqual(g.state.rematch,[])});
test('연결 종료 후 복구 및 저장 상태 재생성',async()=>{const {g,sockets,ctx,tokens,ready}=await fixture();g.state.turn=0;await msg(g,sockets[0],{type:'move',index:112});sockets[0].readyState=3;await g.webSocketClose(sockets[0]);assert.equal(g.state.board[112],1);await msg(g,sockets[1],{type:'move',index:113});assert.equal(g.state.board[113],0);await msg(g,sockets[2],{type:'join',token:tokens[0]});assert.equal(g.state.players.length,2);assert.equal(sockets[2].a.id,g.state.players[0].id);const restored=new GameRoom(ctx);await ready();assert.equal(restored.state.board[112],1);assert.equal(restored.tokens[g.state.players[0].id],tokens[0]);});
test('무승부 및 명시적 퇴장',async()=>{const {g,sockets}=await fixture();g.state.board=Array.from({length:225},(_,i)=>((Math.floor(i/15)+2*(i%15))%4<2?1:2));g.state.board[224]=0;g.state.black=1;g.state.turn=0;await msg(g,sockets[0],{type:'move',index:224});assert.equal(g.state.status,'draw');await msg(g,sockets[0],{type:'leave'});assert.equal(g.state.status,'waiting');assert.equal(g.state.players.length,1);assert(g.state.board.every(x=>!x));});

const at=(r,c)=>r*15+c;
test('렌주룰: 흑 첫 수 중앙, 3-3/4-4/장목 금수, 4-3 허용',async()=>{
 const {g,sockets}=await fixture();g.state.turn=g.state.black=0;
 await msg(g,sockets[0],{type:'move',index:0});assert.equal(g.state.board[0],0);assert.match(sockets[0].out.at(-1).message,/정중앙/);
 await msg(g,sockets[0],{type:'move',index:112});assert.equal(g.state.board[112],1);
 const check=(stones,move)=>{g.state.board=Array(225).fill(0);stones.forEach(i=>g.state.board[i]=1);g.state.board[move]=1;const r=g.blackResult(move,1);g.state.board[move]=0;return r};
 assert.equal(check([at(7,2),at(7,3),at(7,4),at(7,5),at(7,6)],at(7,7)).reason,'장목(6목 이상)');
 assert.equal(check([at(7,6),at(7,8),at(6,7),at(8,7)],at(7,7)).reason,'3-3');
 assert.equal(check([at(7,5),at(7,6),at(7,8),at(5,7),at(6,7),at(8,7)],at(7,7)).reason,'4-4');
 assert.equal(check([at(7,5),at(7,6),at(7,8),at(6,7),at(8,7)],at(7,7)).legal,true);
});
test('렌주룰: 백은 장목으로도 승리',async()=>{const {g}=await fixture();g.state.board=Array(225).fill(0);for(let c=2;c<=7;c++)g.state.board[at(7,c)]=2;assert.equal(g.fiveOrMore(at(7,7),2),true);});
test('HTTP 경로 및 이미지 응답',async()=>{const call=(p,headers)=>worker.fetch(new Request('https://test.local'+p,{headers}),{});assert.equal((await call('/')).status,200);assert.equal((await call('/f1.jpg')).headers.get('content-type'),'image/jpeg');assert.equal((await call('/unknown')).status,404);assert.equal((await call('/room/abc')).status,400);assert.equal((await call('/room/ABC123',{Origin:'https://evil.test'})).status,403);assert.equal((await (await call('/health')).json()).version,'2.7.0');});
